### ISSUE TITLE
Drag-and-drop upload not working for CSV file field

### ISSUE THREAD

**Issue by Toutouwai** [ryancramerdesign/ImportPagesCSV#17]
The drag-and-drop upload is not working for the CSV file field - dragging a file (txt or CSV) to the field does not highlight the field as per a normal file field and dropping the file has no effect.

Tested in Firefox and Chrome on Windows. Module v1.0.6, PW 3.0.59

**Comment by ryancramerdesign** [comment]
Drag and drop is only supported in the page editor at present. Unless I'm
forgetting something, when file fields appear outside the page editor, you
have to use the choose file button.

**Comment by Toutouwai** [comment]
It's no real problem that the drag and drop doesn't work as browsing for a file using the button is fine. It's just that it says "drag and drop files in here" right in the inputfield. I wonder if there's some way for that to be hidden when the inputfield is used outside of Page Edit.

Another thing that isn't a big deal but could be improved is that in PW3 when a file is uploaded the filename is not displayed.

With a file uploaded...
Previous version in PW2.x:
![2017-04-13_222755](https://cloud.githubusercontent.com/assets/1538852/25001228/9cab25d2-2098-11e7-9ce4-2feb6fcadef4.png)

Current version in PW3.x:
![2017-04-13_222741](https://cloud.githubusercontent.com/assets/1538852/25001245/b03222d6-2098-11e7-8255-28be606fcaf5.png)

This isn't an issue when the file field is inside Page Edit, but when the field is outside of Page Edit could something like this be used: https://tympanus.net/Tutorials/CustomFileInputs/ ?
