### ISSUE TITLE
Compatibility check fails

### ISSUE THREAD

**Issue by kixe** [ryancramerdesign/ImportPagesCSV#23]
Please Update compatibility check in modules directory to be compliant with requirements.

![Bildschirmfoto 2020-04-27 um 10 18 38](https://user-images.githubusercontent.com/4683120/80350330-d6d1a680-8870-11ea-8b4a-f113b86da053.png)

**Comment by ryancramerdesign** [comment]
Thanks Christoph, I've corrected that compatibility list for
ImportPagesCSV.

**Comment by kixe** [comment]
Thanks. Closed.
